include(RELEASE_ARTIFACT)
include("$RELEASE_ARTIFACT-client")
include("$RELEASE_ARTIFACT-client-javafx")
include("$RELEASE_ARTIFACT-client-android")
include("$RELEASE_ARTIFACT-server")
include("website")
