version: 2.1

executors:
  linux:
    docker:
      - image: cimg/openjdk:17.0-browsers

jobs:
  unit-test:
    executor: linux
    steps:
      - checkout
      - run: ./gradlew test

workflows:
  build:
    jobs:
      - unit-test
