const val VERSION_GRADLE = "4.6"
const val VERSION_KOTLIN = "1.2.31"
const val VERSION_NOSQL = "0.1-SNAPSHOT"
const val VERSION_COROUTINES = "0.22.5"

const val VERSION_R = "0.8"
const val VERSION_BUILDCONFIG = "0.12"
const val VERSION_PACKR = "0.3"
const val VERSION_KTFX = "0.2.9"
const val VERSION_COMMONS_LANG = "3.7"
const val VERSION_POI = "3.17"

internal const val VERSION_COMMONS_VALIDATOR = "1.6"
internal const val VERSION_GUAVA = "24.1"
internal const val VERSION_JODA = "2.9.9"
internal const val VERSION_LOG4J12 = "1.7.25"
internal const val VERSION_SHADOW = "2.0.2"
internal const val VERSION_JUNIT_PLATFORM = "1.0.0"
internal const val VERSION_SPEK = "1.1.5"
internal const val VERSION_TESTFX = "4.0.13-alpha"
internal const val VERSION_KTLINT = "0.21.0"