const val VERSION_KOTLIN = "1.3.72"
const val VERSION_COROUTINES = "1.3.8"
const val VERSION_NOSQL = "0.1-SNAPSHOT"

const val VERSION_RETROFIT = "2.9.0"
const val VERSION_GSON = "2.8.6"
const val VERSION_GUAVA = "29.0-jre"
const val VERSION_R = "0.2"
const val VERSION_BUILDCONFIG = "0.2"
const val VERSION_PACKR = "0.2"
const val VERSION_KTFX = "8.4.1"
const val VERSION_MAVEN = "3.6.1"
const val VERSION_COMMONS_LANG = "3.11"
const val VERSION_COMMONS_MATH = "3.6.1"
const val VERSION_POI = "4.1.2"

internal const val VERSION_DOKKA = "0.10.1"
internal const val VERSION_CONTROLSFX = "8.40.14"
internal const val VERSION_COMMONS_VALIDATOR = "1.6"
internal const val VERSION_JODA = "2.10.6"
internal const val VERSION_LOG4J12 = "1.7.30"
internal const val VERSION_SHADOW = "4.0.3"
internal const val VERSION_TESTFX = "4.0.16-alpha"
internal const val VERSION_GIT_PUBLISH = "2.1.3"
internal const val VERSION_KTLINT = "0.37.2"