const val VERSION_GRADLE = "4.8"
const val VERSION_KOTLIN = "1.2.50"
const val VERSION_NOSQL = "0.1-SNAPSHOT"
const val VERSION_COROUTINES = "0.23.3"

const val VERSION_RETROFIT = "2.4.0"
const val VERSION_GSON = "2.8.5"
const val VERSION_GUAVA = "25.1-jre"
const val VERSION_R = "0.8"
const val VERSION_BUILDCONFIG = "0.12"
const val VERSION_PACKR = "0.4"
const val VERSION_KTFX = "0.3.2"
const val VERSION_COMMONS_LANG = "3.7"
const val VERSION_COMMONS_MATH = "3.6.1"
const val VERSION_POI = "3.17"

internal const val VERSION_CONTROLSFX = "8.40.14"
internal const val VERSION_COMMONS_VALIDATOR = "1.6"
internal const val VERSION_JODA = "2.9.9"
internal const val VERSION_LOG4J12 = "1.7.25"
internal const val VERSION_SHADOW = "2.0.4"
internal const val VERSION_JUNIT_PLATFORM = "1.0.0"
internal const val VERSION_SPEK = "1.1.5"
internal const val VERSION_TESTFX = "4.0.13-alpha"
internal const val VERSION_KTLINT = "0.23.1"