const val VERSION_GRADLE = "4.10.2"
const val VERSION_KOTLIN = "1.3.0"
const val VERSION_COROUTINES = "1.0"
const val VERSION_NOSQL = "0.1-SNAPSHOT"

const val VERSION_RETROFIT = "2.4.0"
const val VERSION_GSON = "2.8.5"
const val VERSION_GUAVA = "27.0-jre"
const val VERSION_R = "0.2"
const val VERSION_BUILDCONFIG = "0.3"
const val VERSION_PACKR = "0.6"
const val VERSION_KTFX = "8.4.1"
const val VERSION_MAVEN = "3.5.4"
const val VERSION_COMMONS_LANG = "3.8"
const val VERSION_COMMONS_MATH = "3.6.1"
const val VERSION_POI = "4.0.0"

internal const val VERSION_DOKKA = "0.9.17"
internal const val VERSION_CONTROLSFX = "8.40.14"
internal const val VERSION_COMMONS_VALIDATOR = "1.6"
internal const val VERSION_JODA = "2.10.1"
internal const val VERSION_LOG4J12 = "1.7.25"
internal const val VERSION_SHADOW = "2.0.4"
internal const val VERSION_TESTFX = "4.0.15-alpha"
internal const val VERSION_GIT_PUBLISH = "0.3.3"
internal const val VERSION_KTLINT = "0.29.0"