const val kotlinVersion = "1.2.30"
const val nosqlVersion = "0.1-SNAPSHOT"
const val coroutinesVersion = "0.22.4"

const val rVersion = "0.7"
const val buildconfigVersion = "0.12"
const val packrVersion = "0.3"
const val ktfxVersion = "0.2"
const val commonsLangVersion = "3.7"
const val poiVersion = "3.17"

internal const val commonsValidatorVersion = "1.6"
internal const val guavaVersion = "24.1"
internal const val jodaVersion = "2.9.9"
internal const val log4j12Version = "1.7.25"
internal const val shadowVersion = "2.0.2"
internal const val junitPlatformVersion = "1.0.0"
internal const val spekVersion = "1.1.5"
internal const val textFXVersion = "4.0.12-alpha"
internal const val ktlintVersion = "0.20.0"