const val VERSION_GRADLE = "4.10.2"
const val VERSION_KOTLIN = "1.2.71"
const val VERSION_NOSQL = "0.1-SNAPSHOT"
const val VERSION_COROUTINES = "0.30.2"

const val VERSION_RETROFIT = "2.4.0"
const val VERSION_GSON = "2.8.5"
const val VERSION_GUAVA = "26.0-jre"
const val VERSION_R = "0.5"
const val VERSION_BUILDCONFIG = "0.4"
const val VERSION_PACKR = "0.4"
const val VERSION_KTFX = "8.2.0"
const val VERSION_MAVEN = "3.5.4"
const val VERSION_COMMONS_LANG = "3.8"
const val VERSION_COMMONS_MATH = "3.6.1"
const val VERSION_POI = "4.0.0"

internal const val VERSION_CONTROLSFX = "8.40.14"
internal const val VERSION_COMMONS_VALIDATOR = "1.6"
internal const val VERSION_JODA = "2.10"
internal const val VERSION_LOG4J12 = "1.7.25"
internal const val VERSION_SHADOW = "2.0.4"
internal const val VERSION_JUNIT_PLATFORM = "1.0.0"
internal const val VERSION_SPEK = "1.1.5"
internal const val VERSION_TESTFX = "4.0.14-alpha"
internal const val VERSION_KTLINT = "0.29.0"